### ISSUE TITLE
Raise an error when the csv file has header items with same name

### ISSUE THREAD

**Issue by dfurtado** [dfurtado/dataclass-csv#10]
### Description

At the moment the `DataclassReader` behave exactly the same as the `DictReader` when the csv file contains duplicated headers. By default, it will get the value of the last column, for example, assuming that we have a csv file with the following content:
```text
firstname,lastname,age,age
John,Test,41,23
Edit,Test,3,34
```
Using the `DictReader`, we get the values:
```text
[
    OrderedDict([('firstname', 'John'), ('lastname', 'Test'), ('age', '23')]), 
    OrderedDict([('firstname', 'Edit'), ('lastname', 'Test'), ('age', '34')])
]
```
Note the the values for the field `age` are the values of the second `age` column. The `DataclassReader` has the same behaviour, if we would have a data class containing the field `age`, it would get the values of the second age column (23 and 34).

This can easily lead to mistakes and unpredictable results when reading the csv file.

### Proposed behavior

It would be nice if instead of just getting the values of the last column with the same name, the `DataclassReader` could raise an error saying that the "The CSV file {filename} contains duplicated column names: {column names}".

 The `DataclassReader` could also get a boolean argument called `duplicate_columns_error` (we can find a better name) which would disable this verification and have the same behavior as the `DictReader`.

Need also to discuss if it would be better to have this feature disabled or enabled by default.

### Other information
OS: Debian 4.9.130-2
Python version: 3.7.1
dataclass-csv version: 1.0.1

**Comment by dfurtado** [comment]
Hi @schobster, would like to work on this one?

**Comment by schobster** [comment]
Sure @dfurtado , I'd be glad to help out with this one! It may be a stretch for me to complete it before the end of the weekend, but I should be able to work on it early next week.

**Comment by dfurtado** [comment]
Perfect. Thanks a lot! @schobster

**Comment by dfurtado** [comment]
Close by https://github.com/dfurtado/dataclass-csv/pull/42
