### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Dedalios** [dfurtado/dataclass-csv#16]
[dataclass-csv 1.1.2 .docx](https://github.com/dfurtado/dataclass-csv/files/3026626/dataclass-csv.1.1.2.docx)
Example for french documentation

**Comment by dfurtado** [comment]
Hello @Dedalios !

Thank you so much for your contribution to the project. I really appreciate it!
I have had a look in the file that you send and it looks great. Would you be able to do the change directly to a markdown file.

If you fork and clone the project, you can add a new directory called `translations` and add a file called `README-fr.md`. It would be nice to have that structure so translations to more languages could be added to this directory. 

What do you think?

//Daniel

**Comment by dfurtado** [comment]
I'm closing this issue by now, since it would be hard for me to keep a documentation in French up-to-date with the changes in the project.
