### ISSUE TITLE
Support Optional fields

### ISSUE THREAD

**Issue by johnthagen** [dfurtado/dataclass-csv#23]
It would be useful if, rather than having to add a default (potentially meaningless) value to a field, instead you could mark it as [`Optional`](https://docs.python.org/3/library/typing.html#typing.Optional).

```py
from dataclasses import dataclass
from typing import Optional

@dataclass
class User:
    firstname: str
    email: Optional[str]
    age: int
```

If the field is not provided in the row, the field is set to `None`. This will allow for a type-safe way to detect and handle missing values.

**Comment by dfurtado** [comment]
This feature has been already implemented. Closing it.
