### ISSUE TITLE
DataclassWriter

### ISSUE THREAD

**Issue by johnthagen** [dfurtado/dataclass-csv#24]
It would be great if, given a `List[SomeDataclass]` it were possible to write back out a series of `dataclass`es into their corresponding CSV representation.

This would allow someone to read a CSV into `dataclass`es, modify the data in a type safe way, and then write it back out to CSV.

**Comment by denizdogan** [comment]
This is the exact use case I was looking for when I googled "dataclass csv" and found this library :) Hope to see it implemented in the future.

**Comment by dfurtado** [comment]
@denizdogan definitely, I have already start to implement it. It should be out soon

**Comment by dfurtado** [comment]
@denizdogan Released a new version with the `DataclassWriter`  👍🏼
