### ISSUE TITLE
Support frozen dataclasses

### ISSUE THREAD

**Issue by mschwerhoff** [dfurtado/dataclass-csv#26]
Since CSV data is often used without changing it, it would be great if dataclass-csv supported [frozen dataclasses](https://docs.python.org/3/library/dataclasses.html#frozen-instances). This way, users could enjoy the convenience of dataclass-csv and the additional safety of immutable data.

**Comment by dfurtado** [comment]
Hi @mschwerhoff ,

Currently the `dataclass_csv` works well with dataclasses with frozen property set to `True`, see example below:

```python
from dataclass_csv import DataclassReader
from dataclasses import dataclass


@dataclass(frozen=True)
class User:
    name: str
    email: str
    age: int

def main():

    with open("users.csv") as f:
        reader = DataclassReader(f, User)
        users = list(reader)
        user = users[0]
        user.name = "test"

if __name__ == "__main__":
    main()
```
If you run this code it will raise an error:
```text
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    main()
  File "main.py", line 17, in main
    user.name = "test"
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'name'
```
