### ISSUE TITLE
Support 'Path' columns

### ISSUE THREAD

**Issue by hhoeflin** [dfurtado/dataclass-csv#28]
Hi,

thanks for this very nice package. Do you have plans to support more custom fields as well (e.g. by passing in conversion functions?). 

For me, the one type I very often use is "Path" as a lot of csv-files I have reference paths somewhere. Of course I can easily convert later, but if I define a dataclass, would be nice to define it correctly from the start!

Thanks

**Comment by dfurtado** [comment]
Hi @hhoeflin , thank you so much.

Could you provide me with some examples of this use case?

Correct me if I'm wrong, the scenario that you are describing is that you want to modify a value while reading it from the CSV file, is that right?
If that's the case, would work to implement that in the `__post_init__` method of the data class?
For example, let's say I always want to multiple the numbers I read from a CSV by 2, I could do something like:

```python
from dataclasses import dataclass
from dataclass_csv import DataclassReader


@dataclass
class Number:
    val: int

    def __post_init__(self):
        self.val = self.val * 2

def main():

    with open("numbers.csv") as f:
        reader = DataclassReader(f, Number)
        for number in reader:
            print(number)


if __name__ == "__main__":
    main()
```
Output:
```text
Number(val=4)
```

**Comment by hhoeflin** [comment]
Thanks - I did not see post_init. Will give that a try soon!
