### ISSUE TITLE
Report mapping non-existant column

### ISSUE THREAD

**Issue by tewe** [dfurtado/dataclass-csv#34]
The following example from the README works.

```python
import dataclasses
import io

from dataclass_csv import DataclassReader


@dataclasses.dataclass
class User:
    firstname: str
    email: str = "Not specified"


reader = DataclassReader(io.StringIO("firstname,e-mail\nElsa,elsa@test.com"), User)
reader.map("e-mail").to("email")
print(list(reader))  # [User(firstname='Elsa', email='elsa@test.com')]
```

Unfortunately introducing a typo leads to silent data loss.

```python
reader.map("e_mail").to("email")
print(list(reader))  # [User(firstname='Elsa', email='Not specified')]
```

I think **raising when an explicitly mapped column does not occur in the header of the data** would help prevent errors.

**Comment by dfurtado** [comment]
Hello @tewe ! Nice catch! Thanks for reporting this.
I will definitely have a look at this issue. I agree with you, it would be nice to raise an error indicating that the mapped column couldn't be found.

**Comment by dfurtado** [comment]
Merged a fix for this issue. Thanks a lot for reporting it! :+1:
