### ISSUE TITLE
 AttributeError: 'str' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by shineangelic** [dfurtado/dataclass-csv#43]
Hi, not sure I'm missing something, new to the lib. I am having the reported error, on these lines of the lib:

![image](https://user-images.githubusercontent.com/1335156/114246235-67c26480-9992-11eb-864c-3f426bbbce76.png)

is it my fault? My code is like this:

def deserializeFromCsv(self, base_folder: str) -> MondrianAccount:
        with open(base_folder + "FakeAccount.csv") as users_csv:
            reader = DataclassReader(users_csv, MondrianAccount)
            print(reader)
            for row in reader:
                print(row)

        return reader[0]

I'm not using Union, if that helps

**Comment by shineangelic** [comment]
I'm using python 3.9

**Comment by dfurtado** [comment]
Hi @shineangelic thanks for reporting it.

No, you are not doing anything wrong. It's a known bug. 

I'm working on a fix for this bug at the moment and have plans to release a new version very soon.

**Comment by mizarstar** [comment]
Hi @dfurtado, thank you for the prompt answer to @shineangelic. We are looking forward to your fixes.  In the meantime, do you know if there is any workaround so that we can save some time?

**Comment by dfurtado** [comment]
Hello @mizarstar

Unfortunately, I'm not sure there is a workaround but I completed the fix for it I just need to add some unit tests and I will release a new version today or tomorrow.

**Comment by shineangelic** [comment]
thank you very much

**Comment by dfurtado** [comment]
@shineangelic could you send me the version that you are using? 3.9.2?

**Comment by dfurtado** [comment]
@shineangelic  @mizarstar Release version 1.3.0 on PyPI. Thank you so much for reporting the issue.
