### ISSUE TITLE
Type annotations for *args and **kwds

### ISSUE THREAD

**Issue by gschwaer** [dfurtado/dataclass-csv#46]
The type annotations for the DataclassReader are incorrect:

https://github.com/dfurtado/dataclass-csv/blob/872ce021fcda12bc0ccad8fd7719036dc0d87e4c/dataclass_csv/dataclass_reader.py#L48-L59

https://github.com/dfurtado/dataclass-csv/blob/872ce021fcda12bc0ccad8fd7719036dc0d87e4c/dataclass_csv/dataclass_reader.pyi#L5-L16

Even though `*args` and `**kwds` are technically a `List` and a `Dict` respectively, they are not typed the same way. See [mypy docs](https://mypy.readthedocs.io/en/stable/getting_started.html?highlight=kwargs#more-function-signatures) or [PEP-484](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values). Changing both to `Any` solves this problem.

Mypy output when calling the DataclassReader Ctor:
```python
reader = DataclassReader(
    lines,
    MyDataclass,
    delimiter="+",
#             ^ Argument "delimiter" to "DataclassReader" has incompatible type "str"; expected "Dict[str, Any]"
)
```

**Comment by dfurtado** [comment]
Hi @gschwaer 

Thank you so much for reporting this issue. I will look into it and push a new release asap.

//Daniel
